// <auto-generated />
namespace FrontEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    // [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateUsers : IMigrationMetadata
    {
        private readonly ResourceManager resources = new ResourceManager(typeof(CreateBookAuthors));

        string IMigrationMetadata.Id
        {
            get { return "201810260855_CreateUsers"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return resources.GetString("Target"); }
        }
    }
}
